config/routes.rb
Rails.application.routes.draw do

  # get 'welcome/index'

  resources :welcome

  root to: 'schedules#new'
  match '/handle_inbound' => 'schedules#handle_inbound', via: [:get, :post]
  resources :schedules
  patch '/schedules/:id', to: 'schedules#update'

  devise_for :users, :controllers => {
    :confirmations => "confirmations",
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proxy_email.rb
class ProxyEmail < ApplicationRecord
  belongs_to :user
  validates :email, presence: true, uniqueness: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user

  FROM_TIME = (1..11).map{|n| (n.to_s + " AM")} + ["12 PM Noon"] + (1..11).map{|n| (n.to_s+ " PM")} + ["12 AM Midnight"]


  END_TIME = (2..11).map{|n| (n.to_s + " AM")} + ["12 PM Noon"] + (1..11).map{|n| (n.to_s+ " PM")} + ["12 AM Midnight"]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validate :check_domain
  has_many :schedules, dependent: :destroy
  has_many :proxy_emails
  after_create :generate_proxy_email

  def check_domain
    if self.email.include?('gmail') || self.email.include?('yahoo') || self.email.include?('mailinator') || self.email.include?('rediffmail') || self.email.include?('hotmail')
      errors.add(:email, :blank, message: "domain is not valid, Please enter business email.")
    end
  end

  def self.add_schedule_form
    @users = User.all
    @users.each do |user|
      UserMailer.with(user: user).add_schedule_form.deliver
    end
  end

  def self.next_week_schedule
    user = User.find(8)
    UserMailer.with(user: user).ceo_list.deliver
  end

  def generate_proxy_email
    proxy_email = SecureRandom.hex + "@theceomap.com"
    email = ProxyEmail.find_by_email(proxy_email)
    unless email.present?
      self.proxy_emails.create(email: proxy_email)
    else
      generate_proxy_email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :print_message
  # def catch_email
  #   # begin
  #   #   Rails.logger.info("===========Inbound Connected With Our App========================")
  #   # rescue Exception => e
  #   #   Rails.logger.info("===== Error is #{e}================================")
  #   # end
  #   puts "=======apllication controller method============================"
  #   redirect_to handle_inbound_path
  # end

  # before_action :is_signed_in?

  def print_message
    Rails.logger.info("=====Control reached inside app====================")
  end

  def is_signed_in?
    if !user_signed_in?
      redirect_to new_welcome_path
    else
      puts "======================== User Already Signed In ============================="
        # redirect_to new_user_session_path
      # ..proceed to the action intended to call
    end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    root_path
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  skip_before_action :authenticate_user!, :only => :handle_inbound
  skip_before_action :verify_authenticity_token

  def index
    @schedules = current_user.schedules
  end

  def new
    @schedule = Schedule.new
  end

  def create
    if current_user.schedules.map{|p|p.from_time}.include?(params[:schedule][:from_time]) && current_user.schedules.map{|sch|sch.date.to_s}.include?(params[:schedule][:date])
      flash.now[:notice] = 'You have selected this time!'
      redirect_to root_path
    else
      @user = User.find(current_user.id)
      @user_schedule = @user.schedules.new(schedule_params)
      if @user_schedule.save
        redirect_to schedules_path
      else
        redirect_to root_path
      end
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    @schedule.update_attributes(schedule_params)
    @schedule.save
    redirect_to schedules_path
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.delete
    redirect_to root_path
  end


  # Defines our handler for the "inbound" event type.
  # This gets called for every inbound event sent from Mandrill.
  def handle_inbound
    Rails.logger.info("============== Handle Inbound ======================")
    user = User.find(8)
    UserMailer.with(user: user).ceo_list.deliver
  end

  private
  def schedule_params
    params.require(:schedule).permit(:date, :city, :state, :from_time, :end_time)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :position, :company_ticker)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    if !session[:return_to].blank?
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
      # respond_with resource, :location => after_sign_in_path_for(resource)
      if resource.schedules.present?
        redirect_to schedules_path
      else
        redirect_to new_schedule_path
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProxyMail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Email Relay System</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path) %>
            </li>
          <% else %>
            <li>
              <%= link_to('Login', new_user_session_path) %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-4">
      <div class="forms-container">
        <%= form_for @schedule, url: schedule_path do |f| %>
          <div class="form-group field">
            Date: <%= f.text_field :date, required: true, class: "datepicker" %>
          </div>
          <div class="form-group field">
            City: <%= f.text_field :city, required: true %>
          </div>
          <div class="form-group field">
            State : <%= f.text_field :state, required: true %>
          </div>
          <div class="form-group field">
            From Time : <%= f.select :from_time, options_for_select(Schedule::FROM_TIME) %>
          </div>
          <div class="form-group field">
            End Time : <%= f.select :end_time, options_for_select(Schedule::END_TIME) %>
          </div>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#schedule_date').datepicker({
        locale: 'pt-br',
        format: 'yyyy-mm-dd',
        sideBySide: true,
        daysOfWeekDisabled: [0,6]
    });
  });

</script>

app/views/schedules/handle_inbound.html.erb
Neeraj Pathak

app/views/schedules/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1>Schedules List</h1>
            <table border="1">
              <tr>
                <th>Date</th>
                <th>City</th>
                <th>State</th>
                <th>From Time</th>
                <th>End Time</th>
              </tr>
              <% @schedules.each do |shedule| %>
              <tr>
                <td><%= shedule.date %></td>
                <td><%= shedule.city %></td>
                <td><%= shedule.state %></td>
                <td><%= shedule.from_time %></td>
                <td><%= shedule.end_time %></td>
                <!-- <%shedule.created_at.strftime("%I:00")%> -->
                <% if (shedule.created_at >= Time.now - 24.hours) && (Time.now.wday >= 4) && (Time.now.to_time.strftime("%H").to_i < 12) %>
                  <td><%= link_to 'edit', edit_schedule_path(shedule) %>
                    <%= link_to 'Destroy', schedule_path(shedule), method: :delete, data: { confirm: 'Are you sure?' } %>
                  </td>
                <% end %>
              </tr>
              <% end %>
            </table>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/schedules/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-md-offset-4">
      <div class="forms-container">
        <%= form_for @schedule, url: schedules_path do |f| %>
          <div class="form-group field">
            Date: <%= f.text_field :date, required: true, class: "datepicker" %>
          </div>
          <div class="form-group field">
            City: <%= f.text_field :city, required: true %>
          </div>
          <div class="form-group field">
            State : <%= f.text_field :state, required: true %>
          </div>
          <div class="form-group field">
            From Time : <%= f.select :from_time, options_for_select(Schedule::FROM_TIME) %>
          </div>
          <div class="form-group field">
            End Time : <%= f.select :end_time, options_for_select(Schedule::END_TIME) %>
          </div>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#schedule_date').datepicker({
        locale: 'pt-br',
        format: 'yyyy-mm-dd',
        sideBySide: true,
        daysOfWeekDisabled: [0,6]
    });
        // $('#schedule_date').datepicker({
        // minDate: 0,
        // maxDate: '+1w'
        // });

    // var date = new Date();
    // var currentMonth = date.getMonth();
    // var currentDate = date.getDate();
    // var currentYear = date.getFullYear();

    // $('#schedule_date').datepicker({
    //     minDate: new Date(currentYear, currentMonth, currentDate),
    //     dateFormat: 'yy-mm-dd'
    // });

  });
</script>

app/views/welcome/index.html.erb
<% if current_user.present? %>
  <%= current_user.email %>
<% end %>

<h1>Hello, India!</h1>

app/views/welcome/new.html.erb
<script type="text/javascript">
  alert("Hi functionality is working")
</script>